#!/usr/bin/env python3
"""A link-only translation: every symbol build/recomp/gen/table.c exports, with
zero functions. CI links the hosts with it because generated code is never
tracked and the game is never available there. A host running on it fails at
the first guest call with a clear message; it exists to be linked, not run.

    tools/gen_stub_translation.py --out DIR
"""

import argparse
from pathlib import Path
import shutil

ROOT = Path(__file__).resolve().parents[1]

FUNCS_H = """/* generated by tools/gen_stub_translation.py -- link-only stub, do not edit */
#ifndef RECOMP_FUNCS_H
#define RECOMP_FUNCS_H
#include "x86.h"
#include "intrinsics.h"
#endif
"""

TABLE_C = """/* generated by tools/gen_stub_translation.py -- link-only stub, do not edit */
#include <stdio.h>
#include <stdint.h>
#include "funcs.h"

/* The identity fallback the real table carries; a host with an animation clock overrides it. */
__attribute__((weak)) uint32_t recomp_visual_animation_tick(uint32_t tick) { return tick; }

const uint32_t recomp_func_addrs[1] = {0};
const uint32_t recomp_func_count = 0;
const char *recomp_profile_name(uint32_t i) { (void)i; return 0; }
void (*const recomp_base_ptrs[1])(X86 *) = {0};
void (*const recomp_raw_ptrs[1])(X86 *) = {0};
uint8_t recomp_hooked[1];
RecompHookFn recomp_hook_ptrs[1] = {0};
uint32_t recomp_override_count(void) { return 0; }
uint64_t recomp_override_hash(void) { return 0; }
static int32_t recomp_lookup(uint32_t target) { (void)target; return -1; }
int32_t recomp_index_of(uint32_t addr) { return recomp_lookup(addr); }

static void stub_trap(X86 *c, const char *what, uint32_t target)
{
    fprintf(stderr, "[stub translation] %s to %08x: this build has no generated code\\n", what, target);
    c->r[R_EAX] = 0;
}
void recomp_call(X86 *c, uint32_t target) { stub_trap(c, "call", target); }
void recomp_jump(X86 *c, uint32_t target) { stub_trap(c, "jump", target); }
void recomp_unknown_jump(X86 *c, uint32_t target) { stub_trap(c, "unknown jump", target); }
"""


def write(out):
    """Write table.c, funcs.h and a copy of x86.h into `out`."""
    out = Path(out)
    out.mkdir(parents=True, exist_ok=True)
    (out / "funcs.h").write_text(FUNCS_H)
    (out / "table.c").write_text(TABLE_C)
    shutil.copy(ROOT / "runtime/x86.h", out / "x86.h")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, required=True)
    write(parser.parse_args().out)


if __name__ == "__main__":
    main()
