# EmbedFiles.cmake - writes binary files into a C++ source as byte arrays.
#
# Run as a script: cmake -DOUT=<file.cpp> -DNAMESPACE=<ns>
#   -DENTRIES=<symbol>=<path>|<symbol>=<path>... -P EmbedFiles.cmake
# The entries are separated by '|': a ';' does not survive a custom command's
# argument quoting intact.
# Each entry becomes `extern const unsigned char <symbol>[]` and
# `extern const size_t <symbol>_size` in <ns>. The output is a build product;
# the files it embeds are the tracked source.
cmake_minimum_required(VERSION 3.20)
if(NOT OUT OR NOT NAMESPACE OR NOT ENTRIES)
  message(FATAL_ERROR "EmbedFiles.cmake needs OUT, NAMESPACE and ENTRIES")
endif()
set(body "// Generated by cmake/EmbedFiles.cmake. Do not edit.\n#include <cstddef>\n\nnamespace ${NAMESPACE} {\n")
string(REPLACE "|" ";" entries "${ENTRIES}")
foreach(entry IN LISTS entries)
  string(FIND "${entry}" "=" eq)
  if(eq LESS 1)
    message(FATAL_ERROR "EmbedFiles.cmake: '${entry}' is not <symbol>=<path>")
  endif()
  string(SUBSTRING "${entry}" 0 ${eq} symbol)
  math(EXPR from "${eq} + 1")
  string(SUBSTRING "${entry}" ${from} -1 path)
  file(READ "${path}" hex HEX)
  string(LENGTH "${hex}" digits)
  math(EXPR bytes "${digits} / 2")
  # Sixteen bytes a line.
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," hex "${hex}")
  string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n" hex "${hex}")
  string(APPEND body "extern const unsigned char ${symbol}[] = {\n${hex}\n};\n")
  string(APPEND body "extern const size_t ${symbol}_size = ${bytes};\n")
endforeach()
string(APPEND body "} // namespace ${NAMESPACE}\n")
# Only touch the output when it changes, so a reconfigure rebuilds nothing.
if(EXISTS "${OUT}")
  file(READ "${OUT}" previous)
  if(previous STREQUAL body)
    return()
  endif()
endif()
file(WRITE "${OUT}" "${body}")
